### ISSUE TITLE
fork issue

### ISSUE THREAD

**Issue by bebbi** [syzer/JS-Spark#17]
Unhandled rejection TypeError: Incorrect value of args option
    at exports.fork (child_process.js:529:11)
    at tryCatcher (/Mypath/distributedNgram/node_modules/bluebird/js/main/util.js:24:31)
    at ret (eval at <anonymous> (/Mypath/distributedNgram/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:13:23)
    at /Mypath/distributedNgram/node_modules/js-spark/private/src/server/service/fork.js:18:24
    at Function.times (/Mypath/distributedNgram/node_modules/js-spark/node_modules/lodash/dist/lodash.js:6350:25)
    at Object.forkWorker (/Mypath/distributedNgram/node_modules/js-spark/private/src/server/service/fork.js:16:11)
    at module.exports (/Mypath/distributedNgram/node_modules/js-spark/index.js:31:32)
    at Object.<anonymous> (/Mypath/distributedNgram/index.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by syzer** [comment]
fixed for node 0.12.x

**Comment by syzer** [comment]
@bebbi 
fixed by #01997447c05f409f0aa128559317125eaf9f4fc8
